# Generated by Django 5.2 on 2025-04-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
