# Generated by Django 5.2 on 2025-04-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'verbose_name_plural': 'Delivery Addresses'},
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
    ]
